version: "2"
services:
  web:
    build: ./search/backend
    volumes:
      - ./search/backend:/opt/app
    ports:
      - "3000:3000"
    links:
      - rabbitmq
    environment:
      PORT: 3000
      CONNECTION_STRING_DEV: postgres://user:password@db/db
  frontend:
    build: ./frontend/app
    volumes:
      - ./frontend/app:/opt/frontend
    ports:
      - "3001:3001"
    links:
      - mongo
    environment:
      PORT: 3001
  structure:
    image: golang:1.4
    working_dir: /opt/structure
    command: go run main.go
    ports:
      - "3002:3002"
    volumes:
      - ./structure:/opt/structure
    links:
      - db_structure
    environment:
      - DB_NAME=advanced-golang-db
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
  db:
    restart: always
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
  db_structure:
    restart: always
    image: postgres
    expose:
      - "5433"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
  rabbitmq:
      image: rabbitmq:3-management
      ports:
        - "8080:15672"